### PR TITLE
Account for locks to be considered writes.

### LINKED ISSUE #547: Database locking functions use reader, resulting in error
Steps to reproduce:
1. Query `SELECT GET_LOCK( 'test', 60 )` on a production environment (i.e. with a reader DB instance)
2. Observe `Running in read-only mode for query SELECT GET_LOCK` error

Locking functions should use the writer instead of the reader, or error out with a higher-level error like "locking functions not supported on Altis"

Acceptance criteria:

- [ ] ...

### PR DESCRIPTION
**Pull request by shadyvb**
Fixes https://github.com/humanmade/altis-cloud/issues/547
Ref https://github.com/stuttter/ludicrousdb/issues/133

### CODE REVIEW

**Comment by shadyvb** [comment]
@rmccue locks seems quite risky to use in a multiple writer situation, since they seem localized to the single writer instance that picks up the request. Seems like the same issue as local tmp files in a multi-instance web app.

Do we want to disable or maybe at least warn against using them, instead of fixing the compat ? Possibly only when multiple writers are defined ?

**Review by roborourke — APPROVED** [review]

**Comment by rmccue** [comment]
I'd be OK with us not supporting it if it doesn't make sense, but is it used in legitimate use cases anywhere? I've never seen it apart from this one plugin

**Comment by roborourke** [comment]
Might be rare but doesn't mean its usage isn't legitimate. I think it's better to avoid the error, unless there's reason to suspect it could cause problems on the site.

**Comment by shadyvb** [comment]
@roborourke It's the scalability issues that I'm worried about. eg: when there are multiple writers, and one lock created in one writer wouldn't be available on the other, quite similar to tmp files created on web servers, they exist on only one web server, and shouldn't be relied upon in a multi-instance setup. Hence why we don't allow FS writes.

So supporting it says it should always work, and that is not true, unless the locking / unlocking is happening in the same request, which cannot be guaranteed.

**Comment by roborourke** [comment]
Do we have multiple writers? I would rather it not error like this and we prevent or warn about it in a different way that gets exposed to developers, e.g. trigger a warning if a WPDB request is made for locks. In addition we should document that it is not recommended under the cloud limitations section.

**Comment by shadyvb** [comment]
Sounds like multi-writer isn't something we need to consider 👍

**Comment by rmccue** [comment]
My concern personally was more about performance; if locking happens often, then doing that on the writer could overload it. It might still make sense for us to implement a warning in the code review bot for this to recommend against it.

**Pull request merged**
